### PR TITLE
syntax, style, & clarity

### PR DESCRIPTION
**Pull request by brandondrew**
If you're open to more changes, I'd be happy to continue (whenever I can find the time)

### CODE REVIEW

**Comment by piotrmurach** [comment]
Thank you! ❤️ 

By all means please continue!

Related with this very issue, I've started work on a tool to help me out with misspellings etc... called [queen](https://github.com/piotrmurach/queen). If you fancy collaborating, I could do with adding new rules for different English language issues. However, please bear in mind this is very early so I still need to figure out how it will use the rules, combine them and configure. So please watch this space and let me know what you think!

**Comment by brandondrew** [comment]
@piotrmurach  what's the best way to contact you with ideas for Queen?

**Comment by piotrmurach** [comment]
@brandondrew I think the best way is to open issues on the [queen](https://github.com/piotrmurach/queen/issues) project, this way we will have transparency, super easy way to reference lines of code etc... and may potentially get feedback from other interested people. I would suggest to open an issue per each atomic idea to avoid mother-of-all issues. Would that work for you?

**Comment by brandondrew** [comment]
Yes, that makes sense... assuming it's okay for one of the issues to involve defining or clarifying the scope of the sorts of problems that Queen is up for tackling....  (🤔 perhaps an imperial metaphor is in order here, and I should have said *the sorts of territory that Queen is prepared to conquer* 😉).

**Pull request merged**
