### PR TITLE
create file when :force is true in File::create_file

### PR DESCRIPTION
**Pull request by endorama**
Hello, and thanks for this gem.

In using it I found a bug in the behaviour of TTY::File.create_file when the file existed and the `:force` option was specified.

The missing yield was making the :force action behave like :identical or :skip.

I will add tests ASAP.

### CODE REVIEW

**Comment by piotrmurach** [comment]
Thank you! This gem is fairly 'young' so I expect teething problems with options etc... and tests are essential to prevent any future regressions. Once you add a test I will be happy to merge.

**Comment by endorama** [comment]
@piotrmurach I added the relevant spec to `create_file`. Plus I added `/vendor/` folder to gitignore, as is generally used by bundler for dependencies ( I'll remove it if you're not ok with this ).

**Comment by piotrmurach** [comment]
Smashing! ❤️

**Comment by piotrmurach** [comment]
Released `v0.2.1` with your patch. Thanks.

**Comment by endorama** [comment]
Thank you!!

**Pull request merged**
